FROM golang:1.16-alpine as builder

WORKDIR /app

COPY ./swagger/ ./
COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum

RUN go mod download

RUN go build ./main.go

FROM alpine:3.14

WORKDIR /app/
COPY --from=builder /app/main ./main
COPY --from=builder /app/ui ./ui

EXPOSE 8080
ENTRYPOINT /app/main